apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
spec:
  capacity:
    storage: 200Mi
  hostPath:
    path: /data
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
