version: "3.8"

services:
  psql:
    container_name: db
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  django:
    container_name: api
    build:
      context: ./api
    env_file:
      - ./api/.env
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
    depends_on:
      - psql

  react:
    container_name: app
    build:
      context: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/app/src
